version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    ports:
      - 5433:5432
    command: -p 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080